In [2]:
import pandas as pd
import numpy as np
import networkx as nx

In [3]:
df = pd.read_csv('csv/flat-training.csv')

In [4]:
object_columns = []
for column in df.columns:
    if df[[column]].dtypes[0] == 'object':
        object_columns.append(column)

/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':
/tmp/ipykernel_168469/2539580127.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if df[[column]].dtypes[0] == 'object':

In [5]:
nonobject_columns = [x for x in df.columns.tolist() if x not in object_columns]

df_no = df[nonobject_columns]

df_no.corr() > 0.2

,dog,rabbit,deer,panda,hedgehog,squirrel,dolphin,penguin,turtle,elephant,...,apple,honey,pumpkin,button,whistle,marble,wagon,storybook,clover,bubble
dog,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
rabbit,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
deer,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
panda,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
hedgehog,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
squirrel,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
dolphin,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
penguin,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
turtle,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
elephant,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
lamb,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
cow,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
horse,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
mouse,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
guinea,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
chicken,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
sparrow,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
parrot,False,False,False,False,True,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,False
finch,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
canary,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
bee,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
ladybug,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
snail,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
frog,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
cricket,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
wombat,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
zebra,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
flamingo,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
peacock,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
bat,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
fox,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
beaver,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
seal,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
robin,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
loon,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
swan,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,True,False,False,False
goldfish,False,False,False,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
minnow,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
mole,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
shrew,False,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,False,True,False
puffin,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
owl,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,True,False,True,False
bunny,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
bear,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
cub,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
acorn,False,False,False,False,True,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,False
cloud,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
rainbow,False,False,True,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
puddle,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
berry,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
apple,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
honey,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
pumpkin,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
button,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
whistle,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
marble,False,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
wagon,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
storybook,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
clover,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
bubble,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [11]:
df.isna()

,dog,cat,rabbit,deer,panda,koala,otter,hedgehog,squirrel,dolphin,...,blanket,button,whistle,marble,wagon,storybook,candle,clover,bubble,cookie
0,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99996,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99997,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99998,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99999,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False